using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NicaRunner.Infrastructure.Migrations
{
    /// <summary>
    /// Corrige un bug de origen: todas las migraciones anteriores se generaron
    /// con Sqlite como proveedor activo, así que la anotación
    /// "Sqlite:Autoincrement" en cada columna Id nunca se tradujo a identidad
    /// de Postgres (Npgsql la ignora silenciosamente). Sin este fix, cada
    /// columna Id en Postgres queda como INTEGER simple sin generación de
    /// valor — todo INSERT sin Id explícito fallaría en producción.
    /// Verificado corriendo las migraciones completas contra un Postgres 16
    /// real (Docker) antes de desplegar: \d mostraba "Default" vacío en
    /// todas las tablas hasta aplicar este fix.
    /// </summary>
    public partial class FixPostgresIdentityColumns : Migration
    {
        private static readonly string[] TablesWithIntIdPk =
        {
            "Users", "Races", "RaceCategories", "Runners", "Results",
            "ResultAudits", "PublicResultTokens", "NotificationLogs", "RaceJudges"
        };

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
                return;

            foreach (var table in TablesWithIntIdPk)
            {
                migrationBuilder.Sql($"ALTER TABLE \"{table}\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
                migrationBuilder.Sql(
                    $"SELECT setval(pg_get_serial_sequence('\"{table}\"', 'Id'), " +
                    $"COALESCE((SELECT MAX(\"Id\") FROM \"{table}\"), 0) + 1, false);");
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
                return;

            foreach (var table in TablesWithIntIdPk)
            {
                migrationBuilder.Sql($"ALTER TABLE \"{table}\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            }
        }
    }
}
