using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NicaRunner.Infrastructure.Migrations
{
    /// <summary>
    /// Recaída del mismo bug de origen que ya corrigió FixPostgresIdentityColumns
    /// (20260628145438): dos migraciones posteriores a aquel fix se volvieron a generar
    /// con Sqlite como proveedor activo, así que sus columnas Id quedaron otra vez como
    /// INTEGER simple en Postgres — Npgsql ignora en silencio "Sqlite:Autoincrement".
    ///
    ///   - AddAuditLog       (20260713032954) -> AuditLogs.Id
    ///   - AddTimingDisputes (20260802171650) -> TimingDisputes.Id
    ///
    /// Efecto real: TODO insert sin Id explícito falla con
    /// 23502 null value in column "Id" ... violates not-null constraint.
    /// La bitácora nunca llegó a escribir una sola fila contra Postgres.
    ///
    /// Detectado verificando el cierre de carrera contra un Postgres 16 real: la suite
    /// de tests unitarios no lo puede ver porque no toca una base de datos.
    ///
    /// También convierte las columnas de fecha que quedaron como text en esas mismas dos
    /// migraciones. BaselinePostgresModelSnapshot las dejó a propósito para "su propia
    /// migración de datos"; esa migración es esta. El USING ::timestamp castea los
    /// valores existentes (DateTime de .NET se serializa en ISO-8601, que Postgres parsea
    /// sin ambigüedad), así que es seguro tanto con la tabla vacía como con datos.
    /// </summary>
    public partial class FixPostgresIdentityAuditAndDisputes : Migration
    {
        private static readonly string[] TablesWithIntIdPk =
        {
            "AuditLogs", "TimingDisputes"
        };

        private static readonly (string Table, string Column)[] TextColumnsHoldingDates =
        {
            ("AuditLogs", "CreatedAt"),
            ("TimingDisputes", "UpdatedAt"),
            ("TimingDisputes", "ResolvedAt")
        };

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
                return;

            foreach (var table in TablesWithIntIdPk)
            {
                migrationBuilder.Sql($"ALTER TABLE \"{table}\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
                migrationBuilder.Sql(
                    $"SELECT setval(pg_get_serial_sequence('\"{table}\"', 'Id'), " +
                    $"COALESCE((SELECT MAX(\"Id\") FROM \"{table}\"), 0) + 1, false);");
            }

            foreach (var (table, column) in TextColumnsHoldingDates)
            {
                migrationBuilder.Sql(
                    $"ALTER TABLE \"{table}\" ALTER COLUMN \"{column}\" " +
                    $"TYPE timestamp without time zone USING NULLIF(\"{column}\", '')::timestamp without time zone;");
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider != "Npgsql.EntityFrameworkCore.PostgreSQL")
                return;

            foreach (var (table, column) in TextColumnsHoldingDates)
            {
                migrationBuilder.Sql(
                    $"ALTER TABLE \"{table}\" ALTER COLUMN \"{column}\" TYPE text USING \"{column}\"::text;");
            }

            foreach (var table in TablesWithIntIdPk)
            {
                migrationBuilder.Sql($"ALTER TABLE \"{table}\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            }
        }
    }
}
