using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NicaRunner.Infrastructure.Migrations
{
    /// <summary>
    /// Crea la tabla RefreshTokens. La sección de Postgres replica el patrón de
    /// FixPostgresIdentityColumns/DateTimeColumns: como las migraciones se
    /// generan con Sqlite activo, EF emite la tabla con tipos TEXT/INTEGER
    /// que Postgres acepta pero no lee bien con Npgsql (DateTime se lee como
    /// string, Guid igual, Id no autoincrementa). En vez de agregar otro
    /// FixPostgres* aparte, se hace en el mismo Up para que la tabla quede
    /// usable apenas se aplica.
    /// </summary>
    public partial class AddRefreshTokens : Migration
    {
        private const string NpgsqlProvider = "Npgsql.EntityFrameworkCore.PostgreSQL";

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "RefreshTokens",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    UserId = table.Column<int>(type: "INTEGER", nullable: false),
                    TokenHash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: false),
                    FamilyId = table.Column<Guid>(type: "TEXT", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    ExpiresAt = table.Column<DateTime>(type: "TEXT", nullable: false),
                    RevokedAt = table.Column<DateTime>(type: "TEXT", nullable: true),
                    ReplacedByTokenHash = table.Column<string>(type: "TEXT", maxLength: 64, nullable: true),
                    RevokedReason = table.Column<int>(type: "INTEGER", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RefreshTokens", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RefreshTokens_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_RefreshTokens_FamilyId",
                table: "RefreshTokens",
                column: "FamilyId");

            migrationBuilder.CreateIndex(
                name: "IX_RefreshTokens_TokenHash",
                table: "RefreshTokens",
                column: "TokenHash",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_RefreshTokens_UserId",
                table: "RefreshTokens",
                column: "UserId");

            if (migrationBuilder.ActiveProvider == NpgsqlProvider)
            {
                // Identity en el Id — sin esto los INSERT sin Id explícito fallan
                // (mismo bug que FixPostgresIdentityColumns resolvió para el resto).
                migrationBuilder.Sql(
                    "ALTER TABLE \"RefreshTokens\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");

                // DateTime: TEXT → timestamp para que Npgsql lo lea como DateTime.
                migrationBuilder.Sql(
                    "ALTER TABLE \"RefreshTokens\" ALTER COLUMN \"CreatedAt\" TYPE timestamp without time zone " +
                    "USING \"CreatedAt\"::timestamp without time zone;");
                migrationBuilder.Sql(
                    "ALTER TABLE \"RefreshTokens\" ALTER COLUMN \"ExpiresAt\" TYPE timestamp without time zone " +
                    "USING \"ExpiresAt\"::timestamp without time zone;");
                migrationBuilder.Sql(
                    "ALTER TABLE \"RefreshTokens\" ALTER COLUMN \"RevokedAt\" TYPE timestamp without time zone " +
                    "USING \"RevokedAt\"::timestamp without time zone;");

                // Guid: TEXT → uuid. Npgsql mapea Guid<->uuid nativamente; con
                // TEXT cualquier WHERE FamilyId = @p compara strings y rompe con
                // GuidConversionException en SELECT.
                migrationBuilder.Sql(
                    "ALTER TABLE \"RefreshTokens\" ALTER COLUMN \"FamilyId\" TYPE uuid USING \"FamilyId\"::uuid;");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RefreshTokens");
        }
    }
}
